# Generated by Django 5.2.4 on 2025-07-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('task_path', models.CharField(help_text='Import path of the Celery task (e.g., scheduler.tasks.send_email_task)', max_length=255)),
                ('args', models.JSONField(blank=True, help_text='List of positional args for the task', null=True)),
                ('kwargs', models.JSONField(blank=True, help_text='Dict of keyword args for the task', null=True)),
                ('one_off_run_time', models.DateTimeField(blank=True, help_text='If set, task will run once at this datetime (UTC)', null=True)),
                ('cron_expression', models.CharField(blank=True, help_text='Optional: If set, task will run periodically', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['one_off_run_time'], name='scheduler_s_one_off_da0123_idx'), models.Index(fields=['cron_expression'], name='scheduler_s_cron_ex_bd8ffb_idx')],
            },
        ),
    ]
