# Generated by Django 5.2.4 on 2025-07-11 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Scheduled Job', 'verbose_name_plural': 'Scheduled Jobs'},
        ),
        migrations.AddField(
            model_name='scheduledjob',
            name='description',
            field=models.TextField(blank=True, help_text='Optional text description for understanding the job purpose.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='scheduledjob',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='If set, no executions will be scheduled after this datetime (UTC).', null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='scheduledjob',
            name='max_retries',
            field=models.PositiveIntegerField(default=0, help_text='Maximum retry attempts if the task execution fails.', verbose_name='Max Retries'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='args',
            field=models.JSONField(blank=True, help_text='List of positional args for the task', null=True, verbose_name='*args'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='cron_expression',
            field=models.CharField(blank=True, help_text='Optional: If set, task will run periodically', max_length=100, null=True, verbose_name='Cron Expression'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='kwargs',
            field=models.JSONField(blank=True, help_text='Dict of keyword args for the task', null=True, verbose_name='**kwargs'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Run At'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='next_run_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Next Run At'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='one_off_run_time',
            field=models.DateTimeField(blank=True, help_text='If set, task will run once at this datetime (UTC)', null=True, verbose_name='One Off Run Time'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='task_path',
            field=models.CharField(help_text='Import path of the Celery task (e.g., scheduler.tasks.send_email_task)', max_length=255, verbose_name='Task Path'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.CreateModel(
            name='JobExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Datetime when the task execution started.', verbose_name='Started At')),
                ('finished_at', models.DateTimeField(blank=True, help_text='Datetime when the task execution finished (if applicable).', null=True, verbose_name='Finished At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], help_text='Execution result status.', max_length=20, verbose_name='Status')),
                ('result', models.JSONField(blank=True, help_text='Optional result or return value from task execution.', null=True, verbose_name='Result')),
                ('error_message', models.TextField(blank=True, help_text='Optional error message if the task failed.', null=True, verbose_name='Error Message')),
                ('job', models.ForeignKey(help_text='Reference to the parent scheduled job.', on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='scheduler.scheduledjob', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Job Execution Log',
                'verbose_name_plural': 'Job Execution Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
