# Generated by Django 5.2.4 on 2025-07-12 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_scheduledjob_options_scheduledjob_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobExecutionLog',
        ),
    ]
